In [0]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Read the input file and check the data dimension

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [4]:
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/german_credit.csv')

data.head(5)

default  ... foreign_worker
0        0  ...            yes
1        1  ...            yes
2        0  ...            yes
3        0  ...            yes
4        1  ...            yes

[5 rows x 21 columns]

In [0]:
# You can access from https://www.kaggle.com/uciml/german-credit
#Read input file and understand the data
# "default" is my dependent variable

(1000, 21)
Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')


default account_check_status  duration_in_month  \
0        0               < 0 DM                  6   
1        1    0 <= ... < 200 DM                 48   
2        0  no checking account                 12   
3        0               < 0 DM                 42   
4        1               < 0 DM                 24   

                                      credit_history  \
0  critical account/ other credits existing (not ...   
1           existing credits paid back duly till now   
2  critical account/ other credits existing (not ...   
3           existing credits paid back duly till now   
4                    delay in paying off in the past   

                        purpose  credit_amount                      savings  \
0           domestic appliances           1169  unknown/ no savings account   
1           domestic appliances           5951                 ... < 100 DM   
2  (vacation - does not exist?)           2096                 ... < 100 DM   
3              radio/television           7882                 ... < 100 DM   
4                     car (new)           4870                 ... < 100 DM   

    present_emp_since  installment_as_income_perc  \
0       .. >= 7 years                           4   
1  1 <= ... < 4 years                           2   
2  4 <= ... < 7 years                           2   
3  4 <= ... < 7 years                           2   
4  1 <= ... < 4 years                           3   

                   personal_status_sex      ...       present_res_since  \
0                        male : single      ...                       4   
1  female : divorced/separated/married      ...                       2   
2                        male : single      ...                       3   
3                        male : single      ...                       4   
4                        male : single      ...                       4   

                                            property age  \
0                                        real estate  67   
1                                        real estate  22   
2                                        real estate  49   
3  if not A121 : building society savings agreeme...  45   
4                              unknown / no property  53   

   other_installment_plans   housing credits_this_bank  \
0                     none       own                 2   
1                     none       own                 1   
2                     none       own                 1   
3                     none  for free                 1   
4                     none  for free                 2   

                           job people_under_maintenance  \
0  skilled employee / official                        1   
1  skilled employee / official                        1   
2         unskilled - resident                        2   
3  skilled employee / official                        2   
4  skilled employee / official                        2   

                                   telephone foreign_worker  
0  yes, registered under the customers name             yes  
1                                       none            yes  
2                                       none            yes  
3                                       none            yes  
4                                       none            yes  

[5 rows x 21 columns]

### Q1 Randomly select 50% data for this use case( 1 Marks)
###### Hint: Use train_test_split

In [5]:
from sklearn.model_selection import train_test_split
train_data,test_data = train_test_split(data,test_size=0.5,shuffle=True,stratify=data['default'])
print(train_data.shape,test_data.shape)
y_train_data = train_data['default']
x_train_data = train_data.drop('default',inplace=False,axis=1)

(500, 21) (500, 21)


In [0]:
# Lets build a Ensemble model but need to modify the dataset first


### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [6]:
# Print Shape of model data
x_train_data_transform=pd.get_dummies(x_train_data)
x_train_data_transform.shape

(500, 61)

### Check for highly correlated variables but don't required any treatment for this use case

In [7]:
x_train_data_transform.corr()

duration_in_month  ...  foreign_worker_yes
duration_in_month                                            1.000000  ...            0.134983
credit_amount                                                0.652148  ...            0.058475
installment_as_income_perc                                   0.066035  ...            0.117534
present_res_since                                            0.020618  ...            0.060061
age                                                         -0.024401  ...           -0.033647
credits_this_bank                                           -0.045427  ...            0.000610
people_under_maintenance                                    -0.000763  ...           -0.094838
account_check_status_0 <= ... < 200 DM                       0.101454  ...            0.082957
account_check_status_< 0 DM                                 -0.034874  ...           -0.074059
account_check_status_>= 200 DM / salary assignm...          -0.065256  ...           -0.001916
account_check_status_no checking account                    -0.028548  ...           -0.007246
credit_history_all credits at this bank paid ba...           0.042577  ...            0.039489
credit_history_critical account/ other credits ...          -0.045941  ...           -0.037538
credit_history_delay in paying off in the past               0.100925  ...            0.056647
credit_history_existing credits paid back duly ...          -0.063776  ...           -0.028161
credit_history_no credits taken/ all credits pa...           0.077302  ...            0.033985
purpose_(vacation - does not exist?)                         0.049553  ...            0.042833
purpose_business                                             0.154692  ...            0.015415
purpose_car (new)                                           -0.081917  ...           -0.118472
purpose_car (used)                                           0.147720  ...            0.053256
purpose_domestic appliances                                 -0.047844  ...            0.055465
purpose_education                                           -0.070789  ...           -0.071013
purpose_furniture/equipment                                  0.112973  ...            0.017675
purpose_radio/television                                    -0.054881  ...           -0.000883
purpose_repairs                                             -0.098723  ...            0.019381
purpose_retraining                                          -0.087640  ...            0.020956
savings_.. >= 1000 DM                                       -0.011673  ...           -0.034640
savings_... < 100 DM                                        -0.086920  ...           -0.002149
savings_100 <= ... < 500 DM                                  0.024825  ...           -0.015615
savings_500 <= ... < 1000 DM                                -0.049349  ...            0.010989
...                                                               ...  ...                 ...
present_emp_since_.. >= 7 years                              0.065463  ...            0.050785
present_emp_since_... < 1 year                              -0.089026  ...           -0.011083
present_emp_since_1 <= ... < 4 years                        -0.001550  ...           -0.048650
present_emp_since_4 <= ... < 7 years                         0.034119  ...           -0.012061
present_emp_since_unemployed                                -0.031032  ...            0.042017
personal_status_sex_female : divorced/separated...          -0.099935  ...            0.065250
personal_status_sex_male : divorced/separated               -0.041360  ...           -0.017350
personal_status_sex_male : married/widowed                  -0.076511  ...            0.010989
personal_status_sex_male : single                            0.153051  ...           -0.059375
other_debtors_co-applicant                                   0.054295  ...           -0.129283
other_debtors_guarantor                                     -0

### Drop the original variables which are converted to dummy

### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x_train_data_transform,y_train_data,test_size=0.3)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(350, 61) (150, 61) (350,) (150,)


### Q4 Build Random Forest Model( 1 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999

In [0]:
from sklearn.ensemble import RandomForestClassifier
random_forest_model = RandomForestClassifier(n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999)

In [10]:
random_forest_model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
                       oob_score=False, random_state=9999, verbose=0,
                       warm_start=False)

### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [11]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_predicted = random_forest_model.predict(x_test)
print("confusion matrix")
print(confusion_matrix(y_test,y_predicted))
print('')
print("accuracy score")
print(accuracy_score(y_test,y_predicted))

confusion matrix
[[101   7]
 [ 30  12]]

accuracy score
0.7533333333333333


### Q6 Show the list of the features importance( 1 Marks)

In [12]:
importances=random_forest_model.feature_importances_
importances

array([0.07169452, 0.09335959, 0.03042083, 0.03756673, 0.08117873,
       0.01851243, 0.00861661, 0.01571333, 0.0237259 , 0.01062858,
       0.05577899, 0.01065541, 0.0211323 , 0.01035191, 0.01600421,
       0.00851579, 0.00751711, 0.00751961, 0.01965653, 0.00861991,
       0.014665  , 0.00086069, 0.00108034, 0.01308358, 0.00249281,
       0.00071709, 0.00472302, 0.02199147, 0.01027275, 0.00914593,
       0.01690938, 0.01398567, 0.01277715, 0.01689224, 0.01186187,
       0.00877312, 0.0144682 , 0.00745615, 0.00665201, 0.01657811,
       0.00871616, 0.00818812, 0.00869618, 0.01418722, 0.01586996,
       0.01625272, 0.01316144, 0.01964879, 0.01648085, 0.00567035,
       0.00941655, 0.01553967, 0.01408405, 0.01160286, 0.01659041,
       0.00122232, 0.01046504, 0.01359923, 0.01421762, 0.00172871,
       0.00210618])

### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [0]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [0]:
# Use below values
num_folds = 10
seed = 77

In [0]:
#Validate the Random Forest model build above using k fold

In [15]:
k_fold=KFold(n_splits=num_folds,random_state=seed)
scores=cross_val_score(random_forest_model,x_train_data_transform,y_train_data,cv=k_fold)
scores

array([0.72, 0.8 , 0.76, 0.64, 0.8 , 0.76, 0.68, 0.66, 0.76, 0.8 ])

In [0]:
#Calculate Mean score

In [16]:
scores.mean()

0.738

In [0]:
# Calculate score standard deviation using std()

In [17]:
scores.std()

0.05688585061331157

# Q8 Print the confusion matrix( 1 Marks)

In [18]:
confusion_matrix(y_test,y_predicted)

array([[101,   7],
       [ 30,  12]])

# Q9.Classification accuracy: 
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
( 1 Marks)

In [0]:
from sklearn.metrics import recall_score,precision_score

In [20]:
print('recall {}'.format(recall_score(y_test,y_predicted)))
print('precision {}'.format(precision_score(y_test,y_predicted)))

recall 0.2857142857142857
precision 0.631578947368421


# Q10.Plot Receiver Operating Characteristic (ROC) Curves( 1 Marks)

In [0]:
#Hint: Use roc_curve

In [21]:
from sklearn.metrics import roc_curve
roc_curve(y_test,y_predicted)

(array([0.        , 0.06481481, 1.        ]),
 array([0.        , 0.28571429, 1.        ]),
 array([2, 1, 0]))

ROC curve can help you to choose a threshold that balances sensitivity and specificity in a way that makes sense for your particular context

# Q11. Calculate AUC(the percentage of the ROC plot that is underneath the curve) - optional

In [0]:
from sklearn.metrics import roc_auc_score

In [23]:
roc_auc_score(y_test,y_predicted)

0.6104497354497355

### Bootstrapping ( Bonus)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models

In [0]:
# Number of iterations for bootstrapping
bootstrap_iteration = 10
accuracy = []

In [29]:
from sklearn.utils import resample
from sklearn.metrics import accuracy_score

for i in range(bootstrap_iteration):
    X_, y_ = resample(X_train, y_train)
    rfm.fit(X_, y_)
    y_pred = rfm.predict(X_test)
    
    acc = accuracy_score(y_pred, y_test)
    accuracy.append(acc)

NameError: ignored

In [26]:
accuracy = np.array(accuracy)
print('Accuracy Score')
print('Avearge: ', accuracy.mean())
print('Standard deviation: ', accuracy.std())

Accuracy Score
Avearge:  nan
Standard deviation:  nan
